attempt at fixing unicorn boot time startup and monit support for #329

diff --git a/config/deploy/shared/unicorn_init.sh.erb b/config/deploy/shared/unicorn_init.sh.erb
--- a/config/deploy/shared/unicorn_init.sh.erb
+++ b/config/deploy/shared/unicorn_init.sh.erb
@@ -1,86 +1,73 @@
 #!/bin/sh
-set -e
 
-# Feel free to change any of the following variables for your app:
-TIMEOUT=${TIMEOUT-60}
+### BEGIN INIT INFO
+# Provides:          unicorn
+# Required-Start:    $all
+# Required-Stop:     $network $local_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: starts the unicorn web server
+# Description:       starts unicorn
+### END INIT INFO
+
+# Change these to match your app:
+USER=<%= fetch(:deploy_user) %>
+ENV=<%= fetch(:rails_env) %>
+RBENV_RUBY_VERSION="2.1.1"
 APP_ROOT=<%= current_path %>
-PID_DIR=$APP_ROOT/tmp/pids
-PID=$PID_DIR/unicorn.pid
-CMD="cd $APP_ROOT;  bundle exec unicorn -D -c <%= "#{shared_path}/config/unicorn.rb" %> -E <%= fetch(:rails_env) %>"
-AS_USER=<%= fetch(:deploy_user) %>
-set -u
 
-OLD_PIN="$PID.oldbin"
+# env
+RBENV_ROOT="/home/$USER/.rbenv"
+PATH="$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH"
+SET_PATH="cd $APP_ROOT; rbenv rehash; rbenv local $RBENV_RUBY_VERSION"
+DAEMON="bundle exec unicorn"
+DAEMON_OPTS="-c <%= "#{shared_path}/config/unicorn.rb" %> -E $ENV -D"
+CMD="$SET_PATH; $DAEMON $DAEMON_OPTS"
+NAME=unicorn
+PID="$APP_ROOT/tmp/pids/unicorn.pid"
+OLD_PID="$PID.oldbin"
 
+cd $APP_ROOT || exit 1
+ 
 sig () {
-  test -s "$PID" && kill -$1 `cat $PID`
+        test -s "$PID" && kill -$1 `cat $PID`
 }
-
+ 
 oldsig () {
-  test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
+        test -s $OLD_PID && kill -$1 `cat $OLD_PID`
 }
-
-workersig () {
-  workerpid="$APP_ROOT/tmp/pids/unicorn.$2.pid"
-  
-  test -s "$workerpid" && kill -$1 `cat $workerpid`
-}
-
-run () {
-  if [ "$(id -un)" = "$AS_USER" ]; then
-    eval $1
-  else
-    su -c "$1" - $AS_USER
-  fi
-}
-
-case "$1" in
+ 
+case ${1-help} in
 start)
-  sig 0 && echo >&2 "Already running" && exit 0
-  run "$CMD"
-  ;;
+        sig 0 && echo >&2 "Already running" && exit 0
+        su - $USER -c "$CMD"
+        ;;
 stop)
-  sig QUIT && exit 0
-  echo >&2 "Not running"
-  ;;
+        sig QUIT && exit 0
+        echo >&2 "Not running"
+        ;;
 force-stop)
-  sig TERM && exit 0
-  echo >&2 "Not running"
-  ;;
-kill_worker)
-  workersig QUIT $2 && exit 0
-  echo >&2 "Worker not running"
-  ;;
+        sig TERM && exit 0
+        echo >&2 "Not running"
+        ;;
 restart|reload)
-  sig USR2 && echo reloaded OK && exit 0
-  echo >&2 "Couldn't reload, starting '$CMD' instead"
-  run "$CMD"
-  ;;
+        sig HUP && echo reloaded OK && exit 0
+        echo >&2 "Couldn't reload, starting '$CMD' instead"
+        su - $USER -c "$CMD"
+        ;;
 upgrade)
-  if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
-  then
-    n=$TIMEOUT
-    while test -s $OLD_PIN && test $n -ge 0
-    do
-      printf '.' && sleep 1 && n=$(( $n - 1 ))
-    done
-    echo
-
-    if test $n -lt 0 && test -s $OLD_PIN
-    then
-      echo >&2 "$OLD_PIN still exists after $TIMEOUT seconds"
-      exit 1
-    fi
-    exit 0
-  fi
-  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-  run "$CMD"
-  ;;
-reopen-logs)
-  sig USR1
-  ;;
+        sig USR2 && exit 0
+        echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+        su - $USER -c "$CMD"
+        ;;
+rotate)
+        sig USR1 && echo rotated logs OK && exit 0
+        echo >&2 "Couldn't rotate logs" && exit 1
+        ;;
 *)
-  echo >&2 "Usage: $0 <start|stop|restart|upgrade|force-stop|reopen-logs>"
-  exit 1
-  ;;
+        echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
+        exit 1
+        ;;
 esac
+ 
+exit 0
